os:
  - linux
  - osx
addons:
  apt:
    packages:
      - fakeroot
      - rpm
sudo: required
language: node_js
node_js:
  - "8.6.0"
before_install:
  - npm i -g npm@5.8.0
install:
  - npm ci
  - npm run rebuild
script:
  - npm run make
deploy:
  on:
    tags: true
  provider: releases
  api_key: $GH_TOKEN
  file: out/make/*
  skip_cleanout: true
