os:
  - linux
  - osx
addons:
  apt:
    packages:
      - fakeroot
      - rpm
sudo: required
language: node_js
node_js:
  - "8.6.0"
before_install:
  - npm i -g npm@5.8.0
install:
  - npm ci
  - npm run rebuild
script:
  - npm run make
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: out/make/**/*
  skip_cleanup: true
  on:
    tags: true
