os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - "8.6.0"
before_install:
  - npm i -g npm@5.4.2
install:
  - npm i
  - npm run rebuild
script:
  - npm run make
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: out/make/*.zip
  skip_cleanout: true
  on:
    tags: true
