environment:
  nodejs_version: "8.6.0"
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@5.8.0
  - npm cache clean --force
  - npm ci
  - npm run rebuild
test_script:
  - npm run make
build: off
artifacts:
  - path: 'out\make\**\*.*'
deploy:
  on:
    appveyor_repo_tag: true
  release: $(package_version)
  provider: GitHub
  auth_token:
    secure: tMzsqBF5tDxYg/MeL1Pli+OS2VAvkrnYKPf/uMJ4N6MYf55WCGdEBMw64/qE1NS6
  draft: true
  prerelease: false
