environment:
  nodejs_version: "8.6.0"
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@5.4.2
  - npm i
  - npm run rebuild
test_script:
  - npm run make
build: off
deploy:
  release: $(package_version)
  provider: GitHub
  auth_token:
    secure: tMzsqBF5tDxYg/MeL1Pli+OS2VAvkrnYKPf/uMJ4N6MYf55WCGdEBMw64/qE1NS6
  artifact: out\make\**\*.*
  draft: true
  prerelease: false
